'use strict';
// Leitor de planilhas XLSX pequenas com módulos nativos do Node (ZIP + XML).
// Lê a primeira aba em formato OpenXML; não executa fórmulas/macros e não consulta URLs externas.
const zlib = require('zlib');
const MAX_COMPRESSED = 12 * 1024 * 1024, MAX_ENTRY = 35 * 1024 * 1024;
function xmlText(s){return String(s||'').replace(/<[^>]*>/g,'').replace(/&#(x[0-9a-f]+|\d+);|&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos);/gi,(m,n,e)=>{let v=n||e;if(v[0]==='#')v=v.slice(1);const named={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"};if(named[v])return named[v];if(/^x/i.test(v))return String.fromCodePoint(parseInt(v.slice(1),16)||32);if(/^\d+$/.test(v))return String.fromCodePoint(parseInt(v,10)||32);return m})}
function unescapeXml(s){return String(s||'').replace(/&(?:amp|lt|gt|quot|apos|#\d+|#x[0-9a-f]+);/gi,m=>xmlText(m));}
function columnIndex(letters){let n=0;for(const c of letters.toUpperCase())n=n*26+c.charCodeAt(0)-64;return n-1;}
function zipEntries(buffer){if(!Buffer.isBuffer(buffer)||buffer.length>MAX_COMPRESSED)throw Error('Planilha muito grande (máximo 12 MB).');let eocd=-1;for(let p=buffer.length-22;p>=Math.max(0,buffer.length-65557);p--){if(buffer.readUInt32LE(p)===0x06054b50){eocd=p;break;}}if(eocd<0)throw Error('Arquivo não é um XLSX/ZIP válido.');const total=buffer.readUInt16LE(eocd+10),start=buffer.readUInt32LE(eocd+16),files=new Map();if(total>3000)throw Error('Planilha excede o limite de entradas.');let p=start;for(let i=0;i<total;i++){if(p+46>buffer.length||buffer.readUInt32LE(p)!==0x02014b50)throw Error('ZIP inconsistente.');const method=buffer.readUInt16LE(p+10),packed=buffer.readUInt32LE(p+20),unpacked=buffer.readUInt32LE(p+24),nameLen=buffer.readUInt16LE(p+28),extra=buffer.readUInt16LE(p+30),comment=buffer.readUInt16LE(p+32),local=buffer.readUInt32LE(p+42),name=buffer.toString('utf8',p+46,p+46+nameLen);p+=46+nameLen+extra+comment;if(!/^xl\/(sharedStrings\.xml|worksheets\/sheet\d+\.xml)$/.test(name))continue;if(unpacked>MAX_ENTRY||packed>MAX_COMPRESSED||local+30>buffer.length)throw Error('Entrada ZIP excedeu limite.');const n=buffer.readUInt16LE(local+26),x=buffer.readUInt16LE(local+28),from=local+30+n+x;if(from+packed>buffer.length)throw Error('ZIP truncado.');const raw=buffer.subarray(from,from+packed),data=method===0?raw:method===8?zlib.inflateRawSync(raw,{maxOutputLength:MAX_ENTRY}):null;if(!data)throw Error('Método de compressão XLSX não suportado.');files.set(name,data.toString('utf8'));}return files;}
function parseXlsx(buffer){const files=zipEntries(buffer),sheet=[...files.keys()].filter(k=>/^xl\/worksheets\/sheet\d+\.xml$/.test(k)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0]))[0];if(!sheet)throw Error('Nenhuma aba encontrada na planilha.');const shared=[];const s=files.get('xl/sharedStrings.xml')||'';for(const m of s.matchAll(/<si(?:\s[^>]*)?>([\s\S]*?)<\/si>/g)){let value='';for(const t of m[1].matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g))value+=unescapeXml(t[1]);shared.push(value)}const xml=files.get(sheet),rows=[];for(const r of xml.matchAll(/<row\b([^>]*)>([\s\S]*?)<\/row>/g)){const row=[],rowId=Number((r[1].match(/\br="(\d+)"/)||[])[1]||rows.length+1);if(rowId>15000)throw Error('Planilha excede o limite de 15 mil linhas.');for(const c of r[2].matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)){const ref=(c[1].match(/\br="([A-Z]+)\d+"/)||[])[1];if(!ref)continue;const idx=columnIndex(ref);if(idx>140)continue;const type=(c[1].match(/\bt="([^"]+)"/)||[])[1],body=c[2]||'',v=(body.match(/<v>([\s\S]*?)<\/v>/)||[])[1];let val=type==='inlineStr'?([...body.matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(x=>unescapeXml(x[1])).join('')):type==='s'?shared[Number(v||0)]:(v==null?'':unescapeXml(v));if(!['s','inlineStr','str','e'].includes(type)&&val!==''&&Number.isFinite(Number(val)))val=Number(val);row[idx]=val;}while(rows.length<rowId-1)rows.push([]);rows.push(row);}return rows;}
module.exports={parseXlsx};
